name: CI
on:
  workflow_call:
jobs:
  CI:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring
          coverage: none
      - name: Install dependencies
        run: make vendor
      - name: Make
        run: make ci
